// Development-only fixture controls. Not part of the deployed static directory.
import {ATTIRE} from '/campaign.js';
export function installQA({game,view}){
 const panel=document.createElement('section');panel.id='qa-panel';panel.style.cssText='position:fixed;right:12px;top:190px;z-index:100;color:#cfe9d7;background:#080d18f5;border:1px solid #667b8e;padding:12px;width:300px;max-height:70vh;overflow:auto;font:12px/1.6 monospace;pointer-events:auto';
 panel.innerHTML='<strong>V4 development scenarios</strong>'+[['run-qa','Run V4 regression'],['show-city','Show city and girl'],['show-workshop','Show workshop'],['show-boss','Show parry encounter'],['show-fx','Show skill effects'],['show-npc','Show crow hunter']].map(([id,label])=>`<button id="${id}" style="display:block;margin:9px 0">${label}</button>`).join('')+'<pre id="qa-result" style="white-space:pre-wrap">Ready</pre>';document.body.append(panel);
 const out=panel.querySelector('#qa-result'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
 const until=async(fn,label,timeout=6000)=>{let start=performance.now();while(!fn()){if(performance.now()-start>timeout)throw Error(label+' timed out '+JSON.stringify({mode:game.mode,time:game.time,roll:game.p.roll,stamina:game.p.stamina,frames:view.frames}));await sleep(25);}};
 const press=code=>{window.dispatchEvent(new KeyboardEvent('keydown',{code,bubbles:true}));window.dispatchEvent(new KeyboardEvent('keyup',{code,bubbles:true}));};
 const hold=async(code,ms)=>{window.dispatchEvent(new KeyboardEvent('keydown',{code,bubbles:true}));await sleep(ms);window.dispatchEvent(new KeyboardEvent('keyup',{code,bubbles:true}));};
 const assert=(x,label)=>{if(!x)throw Error(label);},pass=t=>out.textContent+='\nPASS '+t;
 const click=async selector=>{await until(()=>document.querySelector(selector),'UI '+selector);document.querySelector(selector).click();await sleep(90);};
 const pos=(x,y=0)=>Object.assign(game.p,{x,y,vx:0,vy:0,ground:true,inv:0,attack:null,roll:0,heal:0,kb:0,climb:null});
 window.addEventListener('error',e=>out.textContent+='\nRUNTIME ERROR '+e.message);
 panel.querySelector('#run-qa').onclick=async()=>{panel.querySelector('#run-qa').disabled=true;out.textContent='Running…';try{
  await view.ready;assert(!view.loadErrors.length,'assets loaded');game.reset();await click('#start');assert(game.dialogue==='intro','opening');await click('[data-choice="wake"]');assert(game.mode==='playing','wake');pass('nine assets / opening / wake');
  press('KeyL');await until(()=>!game.p.roll,'roll release');press('KeyJ');assert(game.p.attack,'attack starts');await until(()=>!game.p.attack,'attack release');press('Space');await until(()=>game.p.y>.4,'jump');await until(()=>game.p.ground,'land');pass('roll / attack / jump release');
  pos(6);game.p.hp=10;press('KeyR');await until(()=>!game.p.heal,'healing end');assert(game.p.hp>10,'heal');const x=game.p.x;await hold('KeyD',300);assert(game.p.x>x+1,'move after heal');pass('heal / movement');
  for(let i=0;i<6;i++){pos(6);await until(()=>game.p.stamina>60&&!game.p.rollCd,'stamina recovery');press('KeyL');await until(()=>!game.p.roll,'repeat roll');press('KeyJ');assert(game.p.attack,'repeat attack');await until(()=>!game.p.attack,'repeat attack end');}pass('six repeated combat cycles / stamina recovery');
  pos(9);press('KeyE');await click('[data-story]');assert(game.flags.gift,'gift');pos(15);press('KeyE');await click('[data-upgrade]');assert(game.p.weapons[3].upgrade===1,'upgrade');await click('[data-socket][data-gem="blood"]');assert(game.p.weapons[3].gem==='blood','socket');await click('[data-hclose]');pass('NPC / workshop / upgrade / socket');
  press('Tab');await click('[data-tab="weapon"]');assert(document.querySelectorAll('.bag-cell:not(.vacant)').length===2,'grid');await click('[data-dual]');assert(game.p.dualWield,'dual');press('Tab');press('KeyV');assert(game.p.transformed,'transform');pass('inventory icons / filter / dual / transform');
  game.enterChapter('yharnam',20);game.enemies.forEach(e=>e.dead=true);await hold('KeyW',800);assert(Math.abs(game.p.y-2.7)<.1,'climb in browser');pos(44,2.8);press('KeyE');await click('[data-story]');assert(game.flags.musicBox,'music');pass('held climb input / girl quest / sharp world labels');
  game.enterChapter('aqueduct',31);game.enemies.forEach(e=>e.dead=true);pos(31,9);press('KeyE');await click('[data-choice="eileen"]');assert(game.flags.wallClimb,'unlock');pos(65);press('KeyE');assert(game.flags.badge,'badge');game.enterChapter('dream',15);game.gold=999;game.materials=99;press('KeyE');await click('[data-craft="cannon"]');assert(game.bag.some(i=>i.weapon===10),'crafted');await click('[data-hclose]');pass('hidden NPC / ability / badge / cannon crafting');
  press('Tab');await click('[data-skill="storm"][data-skill-slot="0"]');assert(game.skillSlots[0]==='storm','skill selection');press('Tab');pass('skill unlock and equipment');
  game.enterChapter('yharnam',12);game.enemies.forEach(e=>e.dead=true);const e=game.enemies[0];Object.assign(e,{dead:false,x:14,y:0,hp:900,maxHp:900,state:'windup',timer:.23,stun:0});pos(12);game.p.dir=1;game.p.gunCd=0;press('KeyF');assert(e.parry>0,'parry');press('KeyJ');assert(!e.parry&&e.hp<800,'visceral');assert(view.fx.some(f=>f.kind==='atlas'&&f.row===0),'parry atlas');pass('parry / visceral / impact effect');
  game.enterChapter('tomb',34);game.p.inv=999;await until(()=>game.bossActive,'boss activate');press('KeyC');assert(game.currentBoss().parry>0,'music');press('Escape');const t=game.time;await sleep(300);assert(game.time===t,'pause');press('Escape');pass('boss / music / pause');
  pos(7);game.activeBoss=null;game.bossActive=false;press('KeyE');await click('[data-hclose]');pos(20);game.p.inv=0;game.gold=220;game.hurt(9999);await click('[data-respawn]');assert(game.chapter==='tomb'&&Math.abs(game.p.x-7)<.5,'respawn lamp');assert(game.p.weapons[3].upgrade===1,'gear retained');pass('death / correct area lamp / gear retained');
  pos(34);game.updateWorld();const boss=game.currentBoss();game.hitEnemy(boss,10000,true,1,1);pos(55,2.3);press('KeyE');assert(game.flags.brooch,'brooch');pos(61);press('KeyE');await click('[data-choice="finish"]');assert(game.flags.complete,'ending');game.enterChapter('yharnam',44);pos(44,2.8);press('KeyE');await click('[data-choice="returnBrooch"]');assert(game.flags.broochReturned,'choice');pass('boss / brooch / chapter ending / return quest');
  const save=game.exportSave();game.importSave(save);assert(game.flags.broochReturned,'saved choice');press('KeyM');await until(()=>document.querySelector('.quest-grid'),'journal');assert(document.querySelectorAll('.quest-grid article').length===5,'quest log');assert(document.querySelector('.chronicle').textContent.includes('胸针'),'lasting history');pass('save / persistent story / map');
  out.textContent+='\nALL 14 V4 BROWSER SCENARIOS PASSED';
 }catch(e){out.textContent+='\nFAIL '+e.message;game.pause();console.error(e);}finally{panel.querySelector('#run-qa').disabled=false;}};
 const scene=(id,x,y=0)=>{game.enterChapter(id,x);pos(x,y);game.p.inv=999;game.enemies.forEach(e=>{e.cooldown=999;e.state='recover';e.timer=999;e.vx=0;});panel.style.display='none';};
 panel.querySelector('#show-city').onclick=()=>scene('yharnam',43,2.8);
 panel.querySelector('#show-npc').onclick=()=>scene('aqueduct',30,9);
 panel.querySelector('#show-workshop').onclick=()=>{game.flags.badge=game.flags.eileen=game.flags.spearPlan=true;game.gold=1600;game.materials=99;for(let weapon=5;weapon<=14;weapon++)if(!game.bag.some(i=>i.weapon===weapon))game.bag.push(game.makeItem({kind:'weapon',weapon,rarity:weapon%5,level:3,affix:'duelist'}));for(const i of ATTIRE)game.bag.push(game.makeItem({...i,rarity:3}));game.enterChapter('dream',15);game.action('interact');panel.style.display='none';};
 panel.querySelector('#show-boss').onclick=()=>{scene('tomb',41);game.updateWorld();const b=game.currentBoss();b.x=43;b.state='windup';b.timer=.25;game.p.dir=1;game.p.gunCd=0;for(let i=0;i<30;i++)view.update(.05);game.action('gun');view.fx.forEach(f=>f.life=f.max*.55);const update=view.update.bind(view);view.update=()=>update(0);game.tick=()=>{};};
 panel.querySelector('#show-fx').onclick=()=>{scene('yharnam',35);for(let i=0;i<30;i++)view.update(.05);game.action('frost');view.fx.forEach(f=>f.life=f.max*.5);const update=view.update.bind(view);view.update=()=>update(0);game.tick=()=>{};};
}
