import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,WEAPONS,LEVEL} from '../dist/engine.js';
const advance=(g,seconds,input={})=>{for(let i=0;i<Math.ceil(seconds*120);i++)g.tick(1/120,input);};
function fixture(){let g=new Game({random:()=>.5});g.start();for(const e of g.enemies)e.dead=true;return g;}
function target(g,{x=5,y=0,type='swordsman',hp=1000}={}){let e=g.enemies[0];Object.assign(e,{x,y,home:x,baseY:y,type,hp,maxHp:hp,dead:false,state:'idle',cooldown:100,stun:0,dir:-1});return e;}
test('physics: double jump, one-way landing, coyote and gap traversal',()=>{let g=fixture();g.action('jump');advance(g,.26);let y=g.p.y;g.action('jump');advance(g,.3);assert(g.p.y>y+1);g.action('jump');assert.equal(g.p.jumps,2);advance(g,2);assert.equal(g.p.y,0);g.p.x=21;g.action('jump');advance(g,.7,{right:true});assert(g.p.x>24);advance(g,1);assert.equal(g.p.y,0);});
test('three-hit chain advances, hits each target once per attack, and expires',()=>{let g=fixture(),e=target(g,{x:4});g.action('attack');advance(g,.40);assert.equal(e.hp,983);g.action('attack');assert.equal(g.p.attack.combo,1);advance(g,.43);let second=e.hp;assert(second<983);g.action('attack');assert.equal(g.p.attack.combo,2);advance(g,.65);assert(e.burn>0);advance(g,1);g.action('attack');assert.equal(g.p.attack.combo,0);});
test('early input is buffered into the next attack',()=>{let g=fixture();g.action('attack');advance(g,.17);g.action('attack');advance(g,.17);assert.equal(g.p.attack.combo,1);});
test('roll cancels attacks and grants bounded invulnerability and cooldown',()=>{let g=fixture();g.action('attack');g.action('roll');assert.equal(g.p.attack,null);assert.equal(g.hurt(20),false);advance(g,.5);assert.equal(g.hurt(20),true);assert.equal(g.p.hp,100);});
test('weapon identities: spear reaches targets beyond sword range',()=>{let a=fixture(),e1=target(a,{x:5.9,type:'archer'});a.equip(1);a.action('attack');advance(a,.28);assert.equal(e1.hp,1000);let b=fixture(),e2=target(b,{x:5.9,type:'archer'});b.p.slots=[0,2];b.equip(2);b.action('attack');advance(b,.28);assert(e2.hp<1000-WEAPONS[2].damage);});
test('blade roll critical is consumed by first attack only',()=>{let g=fixture();g.p.rollCrit=.9;g.action('attack');assert.equal(g.p.attack.rollCritical,true);advance(g,.35);g.action('attack');assert.equal(g.p.attack.rollCritical,false);});
test('healing consumes one flask only on completion and damage interrupts it',()=>{let g=fixture();g.p.hp=50;g.action('heal');advance(g,.4);assert.equal(g.p.flasks,3);g.hurt(10);advance(g,1);assert.equal(g.p.flasks,3);assert.equal(g.p.hp,40);g.action('heal');advance(g,.85);assert.equal(g.p.flasks,2);assert(g.p.hp>40);});
test('chest interaction requires explicit slot replacement and preserves old weapon',()=>{let g=fixture();g.p.x=7;g.action('interact');assert(g.chests[0].open);assert.equal(g.loot.length,1);g.action('interact');assert.equal(g.mode,'loot');assert.equal(g.p.slots[0],0);assert(g.chooseLoot(0));assert.equal(g.p.slots[0],2);assert.equal(g.p.weapons[2].rarity,1);assert.equal(g.loot.length,1);assert.equal(g.loot[0].weapon,0);g.action('attack');g.pause('inventory');g.equip(1);assert.equal(g.p.weapon,1);assert.equal(g.p.attack,null);});
test('armor modifies hp and mitigation; charm affects damage',()=>{let g=fixture();g.loot.push({id:'a',x:3,y:0,kind:'armor',rarity:1});g.action('interact');assert.equal(g.p.maxHp,145);g.hurt(100);assert.equal(g.p.hp,58);g.loot.push({id:'b',x:3,y:0,kind:'charm',rarity:2});g.action('interact');assert.equal(g.statDamage(),23);});
test('shield reduces frontal attacks; combo finisher breaks guard',()=>{let g=fixture(),e=target(g,{x:4,type:'shield'});g.hitEnemy(e,100,false,.2,1);assert.equal(e.hp,955);g.hitEnemy(e,100,false,.8,1);assert.equal(e.hp,855);});
test('burn damage does not reset an enemy windup',()=>{let g=fixture(),e=target(g);e.state='windup';e.timer=.6;e.burn=3;e.burnTick=0;advance(g,.1);assert.equal(e.state,'windup');assert(e.timer<.6);});
test('enemy windup is readable, then deals damage',()=>{let g=fixture(),e=target(g,{x:4});e.cooldown=0;advance(g,.3);assert.equal(e.state,'windup');assert.equal(g.p.hp,120);advance(g,.5);assert(g.p.hp<120);});
test('shockwave damages multiple targets and obeys cooldown',()=>{let g=fixture(),a=target(g,{x:4});let b=g.enemies[1];Object.assign(b,{x:6,y:0,dead:false,hp:100,maxHp:100,stun:0});g.action('skill');assert(a.hp<1000&&b.hp<100);let hp=a.hp;g.action('skill');assert.equal(a.hp,hp);assert.equal(g.p.skillCd,7);});
test('checkpoint replenishes once; boss arena locks, phase changes, exit wins',()=>{let g=fixture();g.p.hp=30;g.p.flasks=0;g.p.x=83;advance(g,.05);assert.equal(g.p.hp,120);assert.equal(g.p.flasks,2);g.p.hp=80;advance(g,.05);assert.equal(g.p.hp,80);let boss=g.enemies.at(-1);boss.dead=false;g.p.x=96;advance(g,.05);assert(g.bossActive);g.p.x=92;advance(g,.05);assert(g.p.x>=94);boss.hp=300;advance(g,.05);assert.equal(boss.phase,2);g.hitEnemy(boss,1000,true,1,1);assert(!g.bossActive);g.p.x=114;advance(g,.05);assert.equal(g.mode,'won');});
test('pause freezes timers and world state; death and restart are valid',()=>{let g=fixture();g.action('skill');g.pause();let t=g.time;advance(g,2,{right:true});assert.equal(g.time,t);assert.equal(g.p.x,3);assert.equal(g.p.skillCd,7);g.resume();g.hurt(500);assert.equal(g.mode,'dead');g.reset();assert.equal(g.mode,'title');assert.equal(g.p.hp,120);assert.equal(g.enemies.filter(e=>!e.dead).length,12);});
test('regression: roll completion releases attack and jump indefinitely',()=>{let g=fixture();g.action('roll');advance(g,1);assert.equal(g.p.roll,0);g.action('attack');assert(g.p.attack);advance(g,.5);g.action('jump');advance(g,.15);assert(g.p.y>.5);});
test('regression: healing completion releases movement, attack, roll and repeat healing',()=>{let g=fixture();g.p.hp=1;g.action('heal');advance(g,1);assert.equal(g.p.heal,0);let x=g.p.x;advance(g,.3,{right:true});assert(g.p.x>x+1);g.action('attack');assert(g.p.attack);advance(g,.5);g.action('roll');assert(g.p.roll>0);advance(g,1);g.p.hp=20;g.action('heal');assert(g.p.heal>0);});
test('regression: attack pressed near end of dodge is retained',()=>{let g=fixture();g.action('roll');advance(g,.27);g.action('attack');advance(g,.12);assert(g.p.attack);});
test('only carried slots can be selected, and cancelling loot preserves ground items',()=>{let g=fixture();g.equip(2);assert.equal(g.p.weapon,0);g.p.x=7;g.action('interact');g.action('interact');assert.equal(g.mode,'loot');g.resume();assert.equal(g.p.slots.length,2);assert.equal(g.loot.length,1);g.action('interact');assert.equal(g.mode,'loot');assert(g.chooseLoot(1));assert.deepEqual(g.p.slots,[0,2]);});
test('same-class loot cannot duplicate weapons across both slots',()=>{let g=fixture();g.loot.push({id:'same',x:3,y:0,kind:'weapon',weapon:0,rarity:2,level:2,affix:'embers'});g.action('interact');assert.equal(g.chooseLoot(1),false);assert.equal(g.mode,'loot');assert(g.chooseLoot(0));assert.equal(g.p.weapons[0].level,2);});
test('affixes change actual hit outcomes rather than labels alone',()=>{let a=fixture(),e=target(a,{x:4,type:'archer'});e.burn=3;e.burnTick=10;a.p.weapons[0].affix='embers';a.action('attack');advance(a,.17);assert.equal(e.hp,977);let b=fixture(),f=target(b,{x:4,type:'archer'});b.p.weapons[0].affix='frost';b.action('attack');advance(b,.17);assert(f.slow>1.8);});
test('scrolls scale matching weapons and add life once',()=>{let g=fixture();g.loot.push({id:'scroll',x:3,y:0,kind:'scroll',rarity:1});const before=g.gearDamage(0),other=g.gearDamage(1);g.action('interact');assert.equal(g.mode,'scroll');assert(g.chooseScroll(0));assert.equal(g.p.stats[0],2);assert(g.gearDamage(0)>before);assert.equal(g.gearDamage(1),other);assert.equal(g.p.maxHp,132);assert.equal(g.chooseScroll(0),false);});
test('frost cooldown and enemy slow both expire cleanly',()=>{let g=fixture(),e=target(g,{x:5,type:'archer'});g.action('frost');assert.equal(g.p.skill2Cd,6);assert.equal(e.slow,3);advance(g,7);assert.equal(g.p.skill2Cd,0);assert.equal(e.slow,0);g.action('frost');assert(e.slow>0);});
